### ISSUE TITLE
启东时没有按照配置的zookeeper找注册中心

### ISSUE THREAD

**Issue by Mrbug001** [apache/incubator-dubbo-ops#26]
我启动的时候总是报失败，看了下日志，是因为注册中心一直找127.0.0.1:2181的，没有按照我配置的ip和端口找dubbo.registry.address=zookeeper://172.18.139.19:2181?backup=172.18.139.20:2181,172.18.139.21:2181

**Comment by mark-wk** [comment]
我这边也是，，有什么解决办法吗

**Comment by ChoingHyun** [comment]
遇到同样问题

**Comment by Mrbug001** [comment]
@ChoingHyun 解决了吗？

**Comment by Mrbug001** [comment]
@mark-wk 解决了吗？

**Comment by xjliang2007** [comment]
dubbo.properties 文件可以放在两个地方，一个是/WEB-INF/dubbo.properties 目录下，一个是当前用户目录下 file://${user.home}/dubbo.properties , 应该只选择一个地方放置就可以了，怀疑是不是有多个地方放置了该文件，导致配置被覆盖了。

**Comment by mark-wk** [comment]
@xjliang2007  /WEB-INF/dubbo.properties 这个目录值得是什么，dubbo-monitor-simple-2.0.0/conf这个目录有， file://${user.home}/dubbo.properties也放了一样的还是不行。。

**Comment by xjliang2007** [comment]
@mark-wk  你要启动的是dubbo-admin 吧，dubbo-admin下的webapp/WEB-INF目录下有一个dubbo.properties文件，你把这个文件的 "dubbo.registry.address" 这项的地址改成你要连接的zk集群地址就好了，file://${user.home}/目录下就不要放dubbo.properties文件了。

**Comment by mark-wk** [comment]
@xjliang2007 不是的，是dubbo-monitor-simple，简单dubbo管理，jetty启动的那个项目。下面是报错信息。java.lang.IllegalStateException: Failed to register dubbo://192.168.111.107:7070/com.alibaba.dubbo.monitor.MonitorService?anyhost=true&application=simple-monitor&delay=-1&dubbo=2.6.0&generic=false&interface=com.alibaba.dubbo.monitor.MonitorService&methods=lookup,collect&owner=dubbo&pid=9508&revision=2.6.0&side=provider&timestamp=1527315834306 to registry 127.0.0.1:2181, cause: Failed to register dubbo://192.168.111.107:7070/com.alibaba.dubbo.monitor.MonitorService?anyhost=true&application=simple-monitor&delay=-1&dubbo=2.6.0&generic=false&interface=com.alibaba.dubbo.monitor.MonitorService&methods=lookup,collect&owner=dubbo&pid=9508&revision=2.6.0&side=provider&timestamp=1527315834306 to zookeeper zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=simple-monitor&client=curator&dubbo=2.6.0&interface=com.alibaba.dubbo.registry.RegistryService&owner=dubbo&pid=9508&timestamp=1527315824245, cause: KeeperErrorCode = ConnectionLoss
        at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:149)
        at com.alibaba.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:116)
        at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:135)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66)
        at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
        at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:505)
        at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:357)

**Comment by madman1990** [comment]
jar包里面读取配置文件默认是读取项目里面的，代码如下。
System.setProperty("dubbo.properties.file", "conf/dubbo.properties");jar包里面有一个conf的文件夹目录，里面有个dubbo.properties文件，我是改了这个文件之后就能正常连接使用了。
