### ISSUE TITLE
启动不了dubbo monitor

### ISSUE THREAD

**Issue by stoneLee81** [apache/incubator-dubbo-ops#27]
下载源码编译成功后,去到dubbo-monitor目录的bin目录，启动start.sh，报错如下：

com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=0, version=2.6.0, twoway=false, event=true, broken=false, data=R] to /10.0.1.9:35286, cause: null
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:106)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.send(HeaderExchangeChannel.java:86)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeServer.sendChannelReadOnlyEvent(HeaderExchangeServer.java:135)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeServer.close(HeaderExchangeServer.java:105)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.destroy(DubboProtocol.java:417)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:104)
        at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:84)
        at com.alibaba.dubbo.config.ProtocolConfig.destroyAll(ProtocolConfig.java:163)
        at com.alibaba.dubbo.config.AbstractConfig$1.run(AbstractConfig.java:82)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:643)
        at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
        at org.jboss.netty.channel.Channels.write(Channels.java:632)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:70)
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:98)
        at org.jboss.netty.channel.Channels.write(Channels.java:611)
        at org.jboss.netty.channel.Channels.write(Channels.java:578)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251)
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:96)

**Comment by nzomkxia** [comment]
dubbo monitor will be part of new dubbo admin
