### ISSUE TITLE
启动报错：Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/FilterChain

### ISSUE THREAD

**Issue by ChoingHyun** [apache/incubator-dubbo-ops#29]
源码编译成功，启动start.sh，报错如下：
`Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
 INFO logger.LoggerFactory - using logger: com.alibaba.dubbo.common.logger.log4j.Log4jLoggerAdapter
 INFO container.Main -  [DUBBO] Use container type([log4j, spring, registry, jetty]) to run dubbo serivce., dubbo version: 2.6.0, current host: 127.0.0.1
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/FilterChain
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.dubbo.container.jetty.JettyContainer.start(JettyContainer.java:56)
	at com.alibaba.dubbo.container.Main.main(Main.java:85)
Caused by: java.lang.ClassNotFoundException: javax.servlet.FilterChain
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
`

**Comment by kingyoungfan** [comment]
我也碰到这个问题，请问解决了吗？

**Comment by hilot** [comment]
https://github.com/apache/incubator-dubbo-ops/issues/6  
remove scope works for me!

**Comment by agthyetal1** [comment]
我也是碰到这个问题，用的jdk8，不知道怎么办

**Comment by renker** [comment]
把 <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>  的scope 移除掉就行了
