### ISSUE TITLE
javax.servlet.api missing

### ISSUE THREAD

**Issue by ayhero** [apache/incubator-dubbo-ops#6]
![qq 20180206113901](https://user-images.githubusercontent.com/4559497/35840742-17f7113a-0b33-11e8-8de7-7e8467307553.png)
as the pic above,if it's not a  bug,please note in the docs,because it just make some trouble in runing

**Comment by chickenlj** [comment]
Do you got this error when using dubbo-admin?
servlet-api is expected to be provided by the containers you use.

**Comment by huanxu20011572** [comment]
scope change  to 'compile' or delete

**Comment by xiaomaijiang** [comment]
same error...

Version:dubbo-monitor 2.0.0
Error Log:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/ServletRequest
        at com.alibaba.dubbo.container.jetty.JettyContainer.start(JettyContainer.java:56)
        at com.alibaba.dubbo.container.Main.main(Main.java:85)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletRequest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more

**Comment by HarvestGolem** [comment]
Delete   <scope>provided</scope>
