### ISSUE TITLE
File: RouteUtils.java Line: 124 Exception: NullPointerException

### ISSUE THREAD

**Issue by DoFunCloud** [apache/incubator-dubbo-ops#65]
`
java.lang.NullPointerException: null
	at com.alibaba.dubboadmin.registry.common.route.RouteUtils.route(RouteUtils.java:124) ~[classes/:na]
	at com.alibaba.dubboadmin.registry.common.route.RouteUtils.route(RouteUtils.java:91) ~[classes/:na]
	at com.alibaba.dubboadmin.web.mvc.governance.ConsumersController.index(ConsumersController.java:118) ~[classes/:na]`

**Comment by nzomkxia** [comment]
please try the new version
